sudo: required

language: node_js

env:
- APP_NAME=ubleipzig/collections-ui

notifications:
  email:
  - chjohnson39@gmail.com

node_js:
  - 8

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_1dff54b1fb99_key -iv $encrypted_1dff54b1fb99_iv -in ./packages/finder/.env.enc -out ./packages/finder/.env -d
  - docker build -t $APP_NAME:$TRAVIS_BUILD_ID .
