version: '3'
services:
  collections-ui:
    image: collections-ui
    build:
      args:
        CIRCLE_BRANCH: $CIRCLE_BRANCH
        REACT_APP_SEARCH_API_HOST: $REACT_APP_SEARCH_API_HOST
        REACT_APP_SEARCH_API_COLLECTION: $REACT_APP_SEARCH_API_COLLECTION
      context: ./packages/collections-ui-app
    container_name: collections-ui-app
    ports:
      - "5000:5000"

